compressionLevel: 0

enableGlobalCache: true

nmMode: hardlinks-local

nodeLinker: node-modules

npmScopes:
  gsap:
    npmAuthToken: bf534bc5-233c-4c11-9f0c-aa48ce384d19
    npmRegistryServer: "https://npm.greensock.com"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

unsafeHttpWhitelist:
  - npm.greensock.com

yarnPath: .yarn/releases/yarn-3.6.3.cjs
